dataset_path: MBZUAI/VideoMathQA
dataset_name: mcq
test_split: test
dataset_kwargs:
  token: False
  cache_dir: videomathqa
  video: True
task: videomathqa_mcq_cot_w_subtitles_think
output_type: generate_until
doc_to_visual: !function utils.videomathqa_doc_to_visual
doc_to_text: !function utils.videomathqa_doc_to_text_subtitle
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: False
process_results: !function utils.videomathqa_process_results
metric_list:
  - metric: videomathqa_perception_score
    aggregation: !function utils.videomathqa_mcq_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    frame_num: 32
    pre_prompt: ""
    post_prompt: "First please perform reasoning, and think step by step to provide best answer to the following question with the option's letter (A, B, C, D or E) from the given choices."
  qwen2_5_vl:
    frame_num: 768
    pre_prompt: ""
    post_prompt: "First please perform reasoning, and think step by step to provide best answer to the following question with the option's letter (A, B, C, D or E) from the given choices."
  gemini_api:
    gemini_api_flag: "full subtitle"
    pre_prompt: ""
    post_prompt: "First please perform reasoning, and think step by step to provide best answer to the following question with the option's letter (A, B, C, D or E) from the given choices."
metadata:
  - version: 0.0
