dataset_path: MBZUAI/VideoMathQA
dataset_name: multi_binary
test_split: test
dataset_kwargs:
  token: False
  cache_dir: videomathqa
  video: True
task: videomathqa_mbin_w_subtitles_think
output_type: generate_until
doc_to_visual: !function utils.videomathqa_doc_to_visual
doc_to_text: !function utils.videomathqa_doc_to_text_subtitle
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: False
process_results: !function utils.videomathqa_process_results
metric_list:
  - metric: videomathqa_perception_score
    aggregation: !function utils.videomathqa_multi_binary_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    frame_num: 32
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter (A or B) from the given choices directly."
  qwen2_5_vl:
    frame_num: 768
    pre_prompt: ""
    post_prompt: "\nPlease think about this question as if you were a human pondering deeply. Engage in an internal dialogue using expressions such as 'let me think', 'wait', 'Hmm', 'oh, I see', 'let's break it down', etc, or other natural language thought expressions. It's encouraged to include self-reflection or verification in the reasoning process. Provide your detailed reasoning between the <think> and </think> tags, and then give your final answer between the <answer> and </answer> tags."
  gemini_api:
    gemini_api_flag: "full subtitle"
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter (A or B) from the given choices directly."
metadata:
  - version: 0.0
