name: video-r2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.11=h22baa00_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py312h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.10.0
      - attrs==25.3.0
      - av==15.1.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - colorama==0.4.6
      - datasets==4.0.0
      - decord==0.6.0
      - dill==0.3.8
      - distro==1.9.0
      - einops==0.8.1
      - evaluate==0.4.5
      - filelock==3.13.1
      - flash-attn==2.8.3
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.1.9
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - idna==3.10
      - iniconfig==2.1.0
      - jinja2==3.1.4
      - jiter==0.10.0
      - lmdb==1.7.3
      - loguru==0.7.3
      - lxml==6.0.1
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - networkx==3.3
      - numpy==2.1.2
      - openai==1.107.2
      - opencv-contrib-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.2
      - peft==0.17.1
      - pillow==11.0.0
      - pluggy==1.6.0
      - portalocker==3.2.0
      - propcache==0.3.2
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - pytorch-triton-rocm==3.3.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.9.1
      - requests==2.32.5
      - rich==14.1.0
      - sacrebleu==2.5.1
      - safetensors==0.6.2
      - scipy==1.16.2
      - six==1.17.0
      - sniffio==1.3.1
      - sqlitedict==2.1.0
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tokenizers==0.21.4
      - torch==2.7.0+rocm6.3
      - torchaudio==2.7.0+rocm6.3
      - torchvision==0.22.0+rocm6.3
      - tqdm==4.67.1
      - transformers==4.51.1
      - triton==3.2.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - xxhash==3.5.0
      - yarl==1.20.1
prefix: /vast/users/salman.khan/miniconda3/envs/viduns
