# Download the clone of scivideobench from mmaaz60/scivideobench and replace the dataset_path to the local directory path.
dataset_path: mmaaz60/scivideobench
dataset_kwargs:
  load_from_disk: True
  token: True
  cache_dir: scivideobench
task: scivideobench
test_split: test
output_type: generate_until
doc_to_visual: !function utils.scivideobench_doc_to_visual
doc_to_text: !function utils.scivideobench_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: false
process_results: !function utils.scivideobench_process_results
metric_list:
  - metric: scivideobench_acc
    aggregation: !function utils.scivideobench_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nAnswer with the option's letter from the given choices directly."
  gpt4v:
    pre_prompt: ""
    post_prompt: "Answer the question with A, B, C, D, E, F, G, H, I or J."
  llava_vid:
    pre_prompt: ""
    post_prompt: "The best answer is:"
metadata:
  version: 0.1