dataset_path: sy1998/MLVU_dev
dataset_kwargs:
  token: True
  cache_dir: mlvu
  video: True
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: False
task: mlvu_dev_think
test_split: test
output_type: generate_until
doc_to_visual: !function utils.mlvu_doc_to_visual_dev
doc_to_text: !function utils.mlvu_doc_to_text
doc_to_target: "answer"
# The return value of process_results will be used by metrics
process_results: !function utils.mlvu_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: mlvu_percetion_score
    aggregation: !function utils.mlvu_aggregate_results_dev
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "\nPlease think about this question as if you were a human pondering deeply. Engage in an internal dialogue using expressions such as 'let me think', 'wait', 'Hmm', 'oh, I see', 'let's break it down', etc, or other natural language thought expressions. It's encouraged to include self-reflection or verification in the reasoning process. Provide your detailed reasoning between the <think> and </think> tags, and then give your final answer between the <answer> and </answer> tags."
  plm:
    pre_prompt: ""
    post_prompt: "\nOnly give the best option."
