group: mvbench_think
task:
  - mvbench_action_sequence_think
  - mvbench_moving_count_think
  - mvbench_action_prediction_think
  - mvbench_episodic_reasoning_think
  - mvbench_action_antonym_think
  - mvbench_action_count_think
  - mvbench_scene_transition_think
  - mvbench_object_shuffle_think
  - mvbench_object_existence_think
  - mvbench_fine_grained_pose_think
  - mvbench_unexpected_action_think
  - mvbench_moving_direction_think
  - mvbench_state_change_think
  - mvbench_object_interaction_think
  - mvbench_character_order_think
  - mvbench_action_localization_think
  - mvbench_counterfactual_inference_think
  - mvbench_fine_grained_action_think
  - mvbench_moving_attribute_think
  - mvbench_egocentric_navigation_think
