dataset_path: lmms-lab/Video-MME
dataset_kwargs:
  token: True
  cache_dir: videomme
  video: True
  # From_YouTube: True
task: videomme_w_subtitle_think
test_split: test
output_type: generate_until
doc_to_visual: !function utils.videomme_doc_to_visual
doc_to_text: !function utils.videomme_doc_to_text_subtitle
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: False
# The return value of process_results will be used by metrics
process_results: !function utils.videomme_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: videomme_perception_score
    aggregation: !function utils.videomme_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    frame_num: 32
    pre_prompt: ""
    post_prompt: "\nPlease think about this question as if you were a human pondering deeply. Engage in an internal dialogue using expressions such as 'let me think', 'wait', 'Hmm', 'oh, I see', 'let's break it down', etc, or other natural language thought expressions. It's encouraged to include self-reflection or verification in the reasoning process. Provide your detailed reasoning between the <think> and </think> tags, and then give your final answer between the <answer> and </answer> tags."
  gemini_api:
    gemini_api_flag: "full subtitle"
  llava_vid:
    frame_num: 768
    pre_prompt: ""
    post_prompt: "\nAnswer the question using a single word or phrase."
  # gpt4v:
  #   pre_prompt: ""
  #   post_prompt: 
  # # qwen_vl:  
  # #   pre_prompt: ""
  # #   post_prompt: " Answer:"
  # # otterhd:
  # #   pre_prompt: ""
  # #   post_prompt: " Answer:"
  # xcomposer2_4khd:
  #   pre_prompt: "[UNUSED_TOKEN_146]user\n"
  #   post_prompt: " Answer this question with A, B, C, or D.[UNUSED_TOKEN_145]\n[UNUSED_TOKEN_146]assistant\n"
metadata:
  - version: 0.0
