dataset_path: mmaaz60/minerva
dataset_name: mcq
test_split: test
dataset_kwargs:
  token: False
  cache_dir: minerva
  video: True
task: minerva
output_type: generate_until
doc_to_visual: !function utils.minerva_doc_to_visual
doc_to_text: !function utils.minerva_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: false
process_results: !function utils.minerva_process_results
metric_list:
  - metric: minerva_perception_score
    aggregation: !function utils.minerva_mcq_aggregate_results
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: "Do not generate any intermediate thinking. \nAnswer with the option's letter (A, B, C, D or E) from the given choices directly."
metadata:
  - version: 0.0
