dataset_path: mmaaz60/MMVU
dataset_kwargs:
  token: True
  cache_dir: mmvu
  video: True
generation_kwargs:
  max_new_tokens: 1024
  temperature: 0
  do_sample: False
task: mmvu_val_think
test_split: validation
output_type: generate_until
doc_to_visual: !function utils.mmvu_doc_to_visual_val
doc_to_text: !function utils.mmvu_doc_to_text
doc_to_target: "answer"

process_results: !function utils.mmvu_process_results

metric_list:
  - metric: accuracy
    aggregation: !function utils.mmvu_aggregate_results_val
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
